library(purrr, verbose = FALSE)
library(purrrlyr, verbose = FALSE)
library(ggplot2, verbose = FALSE)
library(neotoma, verbose = FALSE)
library(plyr, verbose = FALSE)
library(reshape2, verbose = FALSE)
library(mgcv, verbose = FALSE)
library(Bchron, verbose = FALSE)
library(viridis, verbose = FALSE)
library(dplyr, verbose = FALSE)
library(readr, verbose = FALSE)
library(gridExtra, verbose = FALSE)
library(yaml, verbose = FALSE)
library(svglite, verbose = FALSE)
library(rgdal, verbose = FALSE)
library(MASS, verbose = FALSE)
library(gridExtra, verbose = FALSE)

settings <- yaml::read_yaml('settings.yaml')
